FROM tensorflow/tensorflow:nightly-gpu-jupyter

ARG USER_ID=1000
ARG GROUP_ID=1000

USER root
RUN apt-get update

ENV WORKDIR=/notebooks
WORKDIR ${WORKDIR}

COPY ./pip.conf /etc/
COPY ./pip.requirements.txt ${WORKDIR}
RUN pip install -r ${WORKDIR}/pip.requirements.txt

RUN apt-get update -y

# add and change usr:grp
RUN groupadd -g ${GROUP_ID} mygroup
RUN useradd -u ${USER_ID} -g ${GROUP_ID} -m myuser
USER myuser


