version: '3.1'

services:
  gitlab:
    image: gitlab/gitlab-ee:17.4.5-ee.0  # Change to gitlab/gitlab-ce for Community Edition
    # image: gitlab/gitlab-ce:17.4.5-ce.0
    # restart: always
    container_name: gitlab-ee
    hostname: 'gitlab.bubulamb.lol'  # Change to your domain
    ports:
      # - 'server port:container port'
      - '7780:80'                     # HTTP
      - '7443:443'                   # HTTPS
      - '7722:7722'                     # SSH
    volumes:
      - '/home/zqy/learningFile/docker/gitlab/container-ee/config:/etc/gitlab'
      - '/home/zqy/learningFile/docker/gitlab/container-ee/logs:/var/log/gitlab'
      - '/home/zqy/learningFile/docker/gitlab/container-ee/data:/var/opt/gitlab'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        gitlab_rails['gitlab_shell_ssh_port'] = 7722;
        gitlab_rails['lfs_enabled'] = true;
      # GITLAB_OMNITUDE_ROOT_PASSWORD: '2718' 
