version: '3'

services:
  tf-jupyter-gpu:
    build:
      context: .
      dockerfile: Dockerfile.tf.gpu
      args:
        - USER_ID=1000 # 用id -u查看
        - GROUP_ID=1000 # 用id -g查看
    image: bubulamb/tensorflow-jupyter-gpu:2.0

    ports:
      - "8888:8888"
    
    volumes:
    # 修改挂载的磁盘路径
      - /home/zqy/learningFile:/notebooks/learningFile
      # - ../machineLearning/machine-learning-notebook:/notebooks/machine-learning-notebook
      # - ../machineLearning/:/notebooks/machineLearning/
      # - ../deepLearning/:/notebooks/deepLearning/
    working_dir: /notebooks
    
    deploy:
      resources:
        reservations:
          devices:
            - driver: "nvidia"
              count: "all" 
              capabilities: ["gpu"] # 选择分配的GPU

    command: >
      jupyter lab --allow-root --ip=0.0.0.0 
      --NotebookApp.token='' --NotebookApp.password=''
      --no-browser --port=8888
