version: "3.0"

services:
  chaturbate-dvr-web:
    container_name: chaturbate-dvr-web
    image: bubulamb/chaturbate-dvr-web:4.0 # first search local image, if dont exit, build from web.Dockerfile
    build:
      context: .
      dockerfile: web.Dockerfile
    restart: unless-stopped
    environment:
      - GUI_USERNAME=bubu
      - GUI_PASSWORD=2718
      - FILENAME_PATTERN="videos/{{.Username}}/{{.Username}}_{{.Year}}-{{.Month}}-{{.Day}}_{{.Hour}}-{{.Minute}}-{{.Second}}"
      - PORT=8002
    network_mode: "host"  # Share the host's network
    env_file:
      - /home/zqy/.docker/.env
    volumes:
      - "/home/zqy/learningFile/docker/chaturbate/videos-dvr:/usr/src/app/videos/"
