version: '3.8'  # 指定docker-compose文件的版本

# Static Ports
# 8096/tcp is used by default for HTTP traffic. You can change this in the dashboard.
# 8920/tcp is used by default for HTTPS traffic. You can change this in the dashboard.
# 1900/udp is used for service auto-discovery. This is not configurable.
# 7359/udp is also used for auto-discovery. This is not configurable.

services:
  jellyfin2:
    image: jellyfin/jellyfin:2024121605-amd64
    container_name: jellyfin
    user: 1000:1000 # uid:gid
    # network_mode: 'host'
    ports:
      - "8096:8096"
      - "8920:8920"
      - "1900:1900/udp"
      - "7359:7359/udp"
    volumes:
      - /home/zqy/learningFile/docker/jellyfin/config:/config
      - /home/zqy/learningFile/docker/jellyfin/cache:/cache
      - type: bind
        source: /home/zqy/learningFile/docker/jellyfin/media
        target: /media
      - type: bind
        source: /home/zqy/learningFile/docker/jellyfin/media2
        target: /media2
        # read_only: true
      - type: bind
        source: /home/zqy/media/
        target: /home_media
      # Optional - extra fonts to be used during transcoding with subtitle burn-in
      - type: bind
        source: /home/zqy/learningFile/docker/jellyfin/fonts
        target: /usr/local/share/fonts/custom
        # read_only: true
    restart: 'unless-stopped'
    # Optional - alternative address used for autodiscovery
    # environment:
    #   - JELLYFIN_PublishedServerUrl=http://example.com
    # Optional - may be necessary for docker healthcheck to pass if running in host network mode
    # extra_hosts:
    #   - 'host.docker.internal:host-gateway'
