version: '3.8'

services:
  server-dst-admin:
    image: hujinbo23/dst-admin-go:1.3.1
    container_name: server-dst-admin-go  # Rename the container
    ports:
      - "8082:8082"    # TCP port for HTTP service
      - "10999:10999/udp"  # UDP port for additional services
      - "10998:10998/udp"  # caves
    restart: unless-stopped
